[project]
dependencies = [
  "python-dotenv>=1.0.1",
  "titanoboa>=0.2.4",
  "web3>=7.3.1",
]
description = "Add your description here"
name = "boa-favoraties"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"
